services:
  backend:
    container_name: tunetown-backend
    build: backend
    ports:
      - '8080:8080'
    env_file:
      - ./backend/.env
    networks:
      - spring-postgres
    depends_on:
      - postgres
    volumes:
      - ./backend/src:/src
      - ~/.m2:/root/.m2
    command: ./mvnw spring-boot:run

  postgres:
    image: 'postgres:15'
    container_name: postgres
    environment:
      - POSTGRES_DB=tunetown_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - spring-postgres
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ai:
    container_name: tunetown-ai
    build: ai
    ports:
      - '5000:5000'
    env_file:
      - ./ai/.env
    networks:
      - spring-postgres
    depends_on:
      - postgres


volumes:
  postgres_data:

networks:
  spring-postgres:
