spring:
  application:
    name: TuneTown - Backend
  main:
    allow-bean-definition-overriding: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

app:
  cors:
    allowed-origins: http://localhost:3000

# Configurações da API do Spotify
spotify:
  client-id: ${SPOTIFY_CLIENT_ID:client_id}
  client-secret: ${SPOTIFY_CLIENT_SECRET:client_secret}

  # URLs da API
  auth:
    url: http://googleusercontent.com/spotify.com/4
  api:
    url: https://api.spotify.com/v1

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:aws_access_key}
      secret-key: ${AWS_SECRET_KEY:aws_secret_key}
    region: ${AWS_REGION:us-east-2}
    s3:
      bucket: ${AWS_BUCKET:aws_bucket}
