spring:
  application:
    name: TuneTown - Backend

# Configurações da API do Spotify
spotify:
  client-id: ${SPOTIFY_CLIENT_ID:client_id} 
  client-secret: ${SPOTIFY_CLIENT_SECRET:client_secret}
  
  # URLs da API
  auth:
    url: http://googleusercontent.com/spotify.com/4
  api:
    url: https://api.spotify.com/v1
