spring:
  application:
    name: TuneTown - Backend

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/tunetown_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

  sql:
    init:
      mode: always
      data-locations: classpath:seed.sql

app:
  cors:
    allowed-origins: http://localhost:3000

spotify:
  client-id: ${SPOTIFY_CLIENT_ID:spotify_client_id}
  client-secret: ${SPOTIFY_CLIENT_SECRET:spotify_client_id}

  auth:
    url: http://googleusercontent.com/spotify.com/4
  api:
    url: https://api.spotify.com/v1

tmdb:
  api-key: ${TMDB_API_KEY:SEU_TOKEN_AQUI}    

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}

api:
  security:
    token:
      secret: ${API_SECURITY_TOKEN_SECRET:key}

ai:
  service:
    url: ${AI_SERVICE_URL:http://ai:5000}

